apiVersion: apps/v1
kind: Deployment

metadata:
  name: paladin-rails

spec:
  replicas: 1

  selector:
    matchLabels:
      app: paladin-rails

  template:
    metadata:
      labels:
        app: paladin-rails

    spec:
      containers:
        - name: paladin-rails
          image: paladin_practice:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /up
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /up
              port: 80
            failureThreshold: 12
            periodSeconds: 5
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /up
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3

          env:
            - name: RAILS_ENV
              valueFrom:
                configMapKeyRef:
                  name: paladin-config
                  key: RAILS_ENV

            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: paladin-config
                  key: DATABASE_HOST

            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: paladin-config
                  key: DATABASE_PORT
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: paladin-secret
                  key: SECRET_KEY_BASE
